### ISSUE TITLE
problem handling some spec files #@CALIB

### ISSUE THREAD

**Issue by JPHammonds** [prjemian/spec2nexus#105]
I have come across a problem handling some files with a #@CALIB statement

In these files I find something like

#@CALIB 0.0501959 0.0141105 0 mca1 

This fails in spec_common_spec2nexus.py in the process method of SPEC_MCA_Calibration class.  It is trying to split the arguments & map to float with:

        a, b, c = map(float, s)

on line 836 (on the version that I have 2017.317.0.  

I have modified this to:

        a, b, c = map(float, s[0:3])

since you are grabbing only three parameters the mca1 is ignored.

**Comment by prjemian** [comment]
can you send me the data file?

**Comment by JPHammonds** [comment]
Pete,

Here is a file.  Both Phaulo Escalante and I received files with this type of CALIB line.  He got his from Philip Ryan and I got mine from Daniel Haskel.

John
On May 18, 2017, at 9:59 AM, Pete R Jemian <notifications@github.com<mailto:notifications@github.com>> wrote:

can you send me the data file?

**Comment by prjemian** [comment]
The lower case in `#@Calib` (rather than `#@CALIB`) is going to cause trouble.  Is it actually in the data file like that?  Here's the documentation on that: https://certif.com/spec_help/scans.html

**Comment by prjemian** [comment]
OK, can handle that, the RE looks obtuse but it works: `#@[cC][aA][lL][iI][bB]`
