### ISSUE TITLE
Problems accessing SpecDataFileScan.data

### ISSUE THREAD

**Issue by JPHammonds** [prjemian/spec2nexus#107]
I seem to be running into a problem with getting access to the scan.data in a new file.  It almost seems that it is a problem in the order that things are being done.  When trying to access the data element of this file I get an error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hammonds/anaconda/envs/rsMap3D_setup/lib/python2.7/site-packages/spec2nexus/spec.py", line 465, in __getattribute__
    self.interpret()
  File "/Users/hammonds/anaconda/envs/rsMap3D_setup/lib/python2.7/site-packages/spec2nexus/spec.py", line 498, in interpret
    func(self)
  File "/Users/hammonds/anaconda/envs/rsMap3D_setup/lib/python2.7/site-packages/spec2nexus/plugins/unicat_spec2nexus.py", line 83, in postprocess
    label = scan.header.H[row][col]
IndexError: list index out of range

I have simplified this to the following session.  I have been accessing the data in many other files before this.  Note that I can ask for the data element a second time and no problems on the second try.  I have included the problem file.

>>> from spec2nexus.spec import SpecDataFile
>>> sd = SpecDataFile("JL124_1.spc")
>>> sd4 = sd.scans["4"]
>>> sd4.data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hammonds/anaconda/envs/rsMap3D_setup/lib/python2.7/site-packages/spec2nexus/spec.py", line 465, in __getattribute__
    self.interpret()
  File "/Users/hammonds/anaconda/envs/rsMap3D_setup/lib/python2.7/site-packages/spec2nexus/spec.py", line 498, in interpret
    func(self)
  File "/Users/hammonds/anaconda/envs/rsMap3D_setup/lib/python2.7/site-packages/spec2nexus/plugins/unicat_spec2nexus.py", line 83, in postprocess
    label = scan.header.H[row][col]
IndexError: list index out of range
>>> sd4.data
{'scint': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'Epoch': [1034.0, 1035.0, 1037.0, 1038.0, 1039.0, 1040.0, 1041.0, 1042.0, 1043.0, 1044.0, 1045.0, 1046.0, 1047.0, 1048.0, 1049.0, 1050.0, 1051.0, 1052.0, 1053.0, 1054.0, 1056.0, 1057.0], 'filters': [162.0, 162.0, 162.0, 162.0, 162.0, 162.0, 162.0, 162.0, 162.0, 
...
MANY LINES REMOVED
...
, 'trans': [5.9909807e-06, 5.9912698e-06, 5.9912698e-06, 5.9906916e-06, 5.9909808e-06, 5.9912697e-06, 5.9912698e-06, 5.9915589e-06, 5.9912698e-06, 5.9909808e-06, 5.9912698e-06, 5.9912698e-06, 5.9912698e-06, 5.9912697e-06, 5.9909808e-06, 5.9912697e-06, 5.9909807e-06, 5.9912698e-06, 5.9909808e-06, 5.9912698e-06, 5.9906918e-06, 5.9904026e-06]}
 
[JL124_1.spc.zip](https://github.com/prjemian/spec2nexus/files/1056379/JL124_1.spc.zip)

**Comment by JPHammonds** [comment]
Looking more into this there appears to be a mismatch in the number of parameters in the Header's #H lines and the scan's #V lines.

**Comment by prjemian** [comment]
Is this mismatch a case that spec2nexus could handle?  Such as ignoring additional values (#V) or unpopulated labels (#H)>

**Comment by prjemian** [comment]
The error message (`IndexError: list index out of range`) could be more informative such as line numbers for the `#H` and `#V` lines that are involved.

**Comment by JPHammonds** [comment]
I am working on trying to determine this now.  It is looking like a problem that there are too many V values in some rows (although there are also cases where there are more H values as well.  I have manually removed some V values in the spec file and this did seem to allow the data to pass through.  The problem is in postprocess in (at least) unciat_spec2nexus when accessing

                    label = scan.header.H[row][col]

I am still confused why it works a second time through asking for scan.data.

On Jun 7, 2017, at 11:09 AM, Pete R Jemian <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this mismatch a case that spec2nexus could handle? Such as ignoring additional values (#V) or unpopulated labels (#H)>

**Comment by prjemian** [comment]
On 06/07/2017 11:15 AM, John Hammonds wrote:
> I am still confused why it works a second time through asking for 
> scan.data.

I agree this is curious and deserves investigation.  The ZIP file you 
contributed will make a good test case.

**Comment by JPHammonds** [comment]
How do we get things defined in header that do not record values????  Or values recorded with no header def?

I am not that familiar with how spec actually works.


On Jun 7, 2017, at 11:51 AM, Pete R Jemian <notifications@github.com<mailto:notifications@github.com>> wrote:



On 06/07/2017 11:15 AM, John Hammonds wrote:
> I am still confused why it works a second time through asking for
> scan.data.

I agree this is curious and deserves investigation. The ZIP file you
contributed will make a good test case.

**Comment by prjemian** [comment]
Someone changed these but did not start a new spec data file.
This is a known problem that has no other obvious solution.

**Comment by prjemian** [comment]
And now the *Aha!* moment arrives.  In the `#V` lines, the item delimiter is two or more consecutive spaces (a tab, `\t` character can substitute for two spaces).  The code has been relying on `str.split()` to break the line into its parts.  This was, in effect, always a single space.  The data file presented has `#V` lines with both number (as originally intended) and string values (with embedded single spaces).  This is where the mismatch happened between numbers of values in matching `#H` and #V` lines.
