### ISSUE TITLE
specplot_gallery: do not re-plot the entire spec file

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#108]
From Suresh Narayanan:

_One question: I would think it would be good if it did not do the entire spec file each time. I can imagine, writing the last scan plotted to a ENV variable for example and the next time, it starts from that scan again. There is no risk of missing a scan then. Often, we have 5-10K scans in a single spec file._

**Comment by prjemian** [comment]
The algorithm makes some attempt to do what you ask but there is an additional consideration that a scan might have been only partly completed when the last plot was made.  The code should look at the time stamp at the start of each scan (and possibly any comments at the end of each scan) to determine if the plot needs to be refreshed.  Additional data (such as number of scan points) could be cached but the cache would be a new feature.

**Comment by prjemian** [comment]
Issue #126 asks for some indicator that the SPEC file has changed.  (PyMCA watches for change in the file's mtime).  Could be useful here.

**Comment by prjemian** [comment]
Good.  With #126, we now have some attributes that enable this.

attribute | comments
-- | --
`update_available` | tells if the file has been update after it was last `read()`
`last_scan` | scan number of the last scan `read()` previously
`num_lines` | number of lines in file when last `read()`

A process that monitors `update_available` for changes would then:

1. make note of both `last_scan`  and `num_lines`
1. call `read()`
1. if  `num_lines`  *and* `last_scan` are different, resume processing from the previous `last_scan`

Note: 
    The previous `last_scan` is reprocessed since that scan may not have been complete when the file was `read()` previously.

**Comment by prjemian** [comment]
The entire process of calling `read()` has not yet been tested.  That will be part of this issue so that the process described will work as expected.

**Comment by prjemian** [comment]
@sureshnaps,: You raised this issue.
@jilavsky  : This can be used to address a [cpu load](https://github.com/APS-USAXS/livedata/issues/34) issue you identified

**Comment by sureshnaps** [comment]
It is great to see this issue back as a high priority. The approach seems fine. It could even be simpler by just replotting the last scan that was plotted and all the newer ones. Then there is no ambiguity.

**Comment by prjemian** [comment]
Need a way to detect if the file *actually* changed size.  (Sometimes, to rovoke software like this to update again, the file timestamp is modified such as using the `touch` command).

Instead of tracking the number of lines (which requires opening the file and parsing the file for line breaks), track the file size (which can be reported from the file system).

**Comment by prjemian** [comment]
Rephrasing:

With #126 complete, we now have some attributes (of `spec.SpecDataFile()`) that enable this.

attribute | comments
-- | --
`update_available` | tells if the file has been updated after it was last `read()`
`filesize` | size of file when last `read()`
`mtime` | modification time of file when last `read()`
`last_scan` | scan number of the last scan `read()` previously

Open the file (example):

    sdf = spec.SpecDataFile(filename)
    myLastScan = sdf.last_scan

then, monitor (continuing example):

    if sdf.update_available:
        sdf.read()
        plot_scan_and_newer(myLastScan)    # new method
        myLastScan = sdf.last_scan

Note: 
    The previous `last_scan` is reprocessed since that scan may not have been complete when the file was `read()` previously.

**Comment by prjemian** [comment]
@sureshnaps: Consider this scenario.
An additional method of `spec.SpecDataFile` might help:

```
def refresh(self):
    """
    update (refresh) the content if the file is updated

    returns previous last_scan or None if file not updated
    """
    if self.update_available:
        myLastScan = self.last_scan
        sdf.read()
        return myLastScan
    return None
```

Then, the monitor code would be easier:

```
scan_number = sdf.refresh()
if scan_number is not None:
    plot_scan_and_newer(scan_number )    # new method

**Comment by prjemian** [comment]
Per [previous comment here](https://github.com/prjemian/spec2nexus/issues/108#issuecomment-522203437), issue #201 has been filed.

**Comment by sureshnaps** [comment]
yes, that scenario will work good. /usr/bin/stat has some features to show last modified time, etc. but seems like there is stuff in python already

**Comment by prjemian** [comment]
*Always* better to use python library call than `subprocess`: `os.path.getmtime`

**Comment by prjemian** [comment]
This *is* an issue for the `specplot_gallery` module.
