### ISSUE TITLE
Ownership of info between #L/data & #S n

### ISSUE THREAD

**Issue by JPHammonds** [prjemian/spec2nexus#110]
I am posting this one but am unsure if there is a clear answer or if it will come down to a judgement call.  I have included an example file as reference.  If you look at some of the scans, I'll point to 139 since this is the one that I am looking at, there are lines starting with #CCD that come between the data (#L/data/#C) from scan 138 and #S for line scan 139.  Looking at the spec documentation, it looks like #C lines can be interspersed with the data.  According to 

https://certif.com/spec_manual/user_1_4_1.html

The data continues until the next non-comment line or a blank line (next to last paragraph)

This seems to leave the data in-between this and the start of the next scan ambiguous.  I do not have access to C_PLOT or scans.4 programs mentioned in the manual to see how/if these lines are handled.  Perhaps these programs would give an answer.

Note that the #CCD are handled in the XPCS plugin and go into file.scans['139'].CCD. 

The information that goes into this is for the next scan if the info lies between the data and the start of the scan.

[bnt5bt.spec.zip](https://github.com/prjemian/spec2nexus/files/1136372/bnt5bt.spec.zip)

**Comment by prjemian** [comment]
PyMCA is another program that reads SPEC data files.  Interesting to see how that program handles this data.

It derives its code base from ESRF's newplot, but that might also be interesting.

**Comment by JPHammonds** [comment]
pyMCA seems to handle it the same way.  I am not really sure that it can be handled much differently in spec2nexus reader but thought that I would throw this out there.  spec2nexus takes a tree-like approach to building the object.  With that, nothing can exist until the lower level branches exist, in this case, that the scan is defined before items in the scan.  I believe that this spec file is created by a real spec macro.  Not knowing much about the macro language it is a bit harder know much about this.  Since scans.4 and C-PLOT come from same company, I was curious as to how they would handle this, if at all.  My read of the manual leaves this case up for grabs.  Seeing how Certified might handle this case would be a bit more defining.  In any event, I will see if I can get the beam line to change this so that future files are more concrete.

**Comment by prjemian** [comment]
I believe I made an assumption that `#S` control lines always have a blank line preceding.  This file clearly does not obey that imagined rule.  The scan starts with the `#S` line, everything before that is from activities before the scan macro was called.  Usually, this is from a previous scan but also may be triggered by command line actions.  The `qdo` most often registers data in data files that is unexpected for a scan.

BUT, this file was written by custom macros that operate a CCD camera and have generated output that labels itself as part of the upcoming scan but appears *before* the `#S` line.

I don't see how to second-guess this content in a general way.  The `SPEC_Scan` plugin has this documentation:

    In SPEC data files, the ``#S`` control line indicates the 
    start of a *scan* block.

**Comment by JPHammonds** [comment]
Pete,

I agree here.  I am sure people will have this going either way.

Is the comment from SPEC_Scan plugin out of the manual?  If it is then the issue is very clear and the use case from sector 8 is in error.  My read of the docs shows that #S is the first line of a scan header (first page of 1.4.1) and “Starts a new scan” (sect 1.4.2.3)  which leans stronger to the statement.

John

On Jul 11, 2017, at 12:02 AM, Pete R Jemian <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't see how to second-guess this content in a general way. The SPEC_Scan plugin has this documentation:

In SPEC data files, the ``#S`` control line indicates the
start of a *scan* block.
