### ISSUE TITLE
problems with reading sardana spec files

### ISSUE THREAD

**Issue by jkotan** [prjemian/spec2nexus#122]
During my tests I wanted to read a SPEC file created by [sardana](https://github.com/sardana-org/sardana/blob/develop/src/sardana/macroserver/recorders/storage.py#L270) , i.e. SCADA software developed at ALBA and hardly used by us (DESY) and other facilities, i.e. ALBA, MAX IV, SOLARIS, ...

I get the following error:

    /home/jkotan/testinst/lib/python2.7/site-packages/spec2nexus-2017.901.4+10.g0ad8aa6-py2.7.egg/spec2nexus/spec.pyc in __init__(self, filename)
	207             raise SpecDataFileNotFound('file does not exist: ' + str(filename))
	208         if not is_spec_file(filename):
    --> 209             raise NotASpecDataFile('not a SPEC data file: ' + str(filename))
	210         self.fileName = filename
	211 

    NotASpecDataFile: not a SPEC data file: /home/jkotan/ndts/file-examples/spec/my.spec

A file example  can be found at  [here](https://github.com/jkotan/file-examples/blob/master/spec/my.spec)

**Comment by prjemian** [comment]
The file example you described does not adhere to the specifications of the SPEC standard data file format.  Please consult the SPEC manual and construct SPEC data files using the [Standard Data File Format](https://certif.com/spec_manual/user_1_4_1.html).

This is a *fragment* of a SPEC data file.  It only includes the scans but not the header lines of the file.

``spec2nexus`` requires that SPEC data files begin with these four control lines: ``#F``, ``#E``, ``#D``, ``#C``.  Without these control lines, as described in the SPEC standard  data file format, ``spec2nexus`` will not identify this file as a SPEC file and raise the ``NotASpecDataFile`` exception.

**Comment by prjemian** [comment]
@mrosanes : please take a look at this

I believe I can support reading of such files (by providing some default header when neon has been found).  This is not specific to Sardana.

**Comment by cpascual** [comment]
Hi, it seems that the missing file header is **not** mandatory (https://github.com/sardana-org/sardana/issues/735#issuecomment-382312675). while we could add it in Sardana, IMHO more generic files should be supported in spec2nexus.

Note: have you considered using silx? For example, the [silx.io.open](http://www.silx.org/doc/silx/latest/modules/io/) function already allows you to access a spec file as if it was a nexus one.

**Comment by prjemian** [comment]
Was not aware of silx.  That's an interesting project.  I'll take a look at its capabilities.  Looks like it's a couple years old and has brought in a much larger team.  This project is quite a bit older but single programmer.

**Comment by cpascual** [comment]
>  Looks like it's a couple years old and has brought in a much larger team

Yes. It is a big commitment from ESRF (@vasole is behind it)
