### ISSUE TITLE
Feature suggestion:  Monitor for file change???

### ISSUE THREAD

**Issue by JPHammonds** [prjemian/spec2nexus#126]
Just a thought, ever think about adding code in the SpecDataFile to monitor for changes in the file & send out a signal?  Since this is a file that is expected to change it might be good to add monitoring so that Apps could take advantage of this.

**Comment by prjemian** [comment]
Where's the event loop running?  Perhaps SpecDataFile would have a boolean @property method named `update_available` to be called from the event loop.  Each time the `read()` method is called, the internal flag is reset.  Internal flag is based on file's mtime and/or checksum.  Thoughts.

**Comment by prjemian** [comment]
It's a good suggestion.  There is no dependence now on Qt and this would be the only justification to add it.  The could could be used now in Qt, wx, Tk, or any other framework.  The clean interface, to avoid introducing a Qt dependency, is to make the method suggested above, to be called by code that watches for file updates.  If there was a POSIX way to generate signals or callbacks based on file system updates, fantastic.  Don't know about that one yet.  It's the automation that is the core of this, the rest seems easy.  So far, that belongs to the client of SpecDataFile().

**Comment by prjemian** [comment]
The proposed `update_available` boolean property might be useful with issue #108.

**Comment by prjemian** [comment]
might be good to also keep track of the number of lines and the last scan number (which could inform #108)
