### ISSUE TITLE
Uxml writer() needs to be implemented

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#159]

**Comment by prjemian** [comment]
@JPHammonds Do you know if this plugin is used?  If not, seems a good candidate to deprecate, then remove.

**Comment by JPHammonds** [comment]
I'll have to look at it.  I believe it was for either Sector 33 or Sector 7.  This was for rsMap most likely.  If for 33 then it is needed.  Not next to the computer now.

On Jul 9, 2019 6:34 PM, Pete R Jemian <notifications@github.com> wrote:

@JPHammonds<https://github.com/JPHammonds> Do you know if this plugin is used? If not, seems a good candidate to deprecate, then remove.

**Comment by JPHammonds** [comment]
Pete,

This plugin was for sector 8.  I am not sure how often this is used but I think that it is used intermittently.

John

From: "JPHammonds@anl.gov" <jphammonds@anl.gov>
Date: Tuesday, July 9, 2019 at 7:51 PM
To: prjemian/spec2nexus <reply@reply.github.com>
Cc: prjemian/spec2nexus <spec2nexus@noreply.github.com>, Mention <mention@noreply.github.com>
Subject: Re: [prjemian/spec2nexus] Uxml writer() needs to be implemented (#159)

I'll have to look at it.  I believe it was for either Sector 33 or Sector 7.  This was for rsMap most likely.  If for 33 then it is needed.  Not next to the computer now.

On Jul 9, 2019 6:34 PM, Pete R Jemian <notifications@github.com> wrote:

@JPHammonds<https://github.com/JPHammonds> Do you know if this plugin is used? If not, seems a good candidate to deprecate, then remove.

**Comment by prjemian** [comment]
@JPHammonds : this was for Christian Schleputz.  I'd be interested to know who at 8ID say they use it.  The code has not been usable for some years now.  Now, the code is working, at least for the few valid test files in the repository.

**Comment by JPHammonds** [comment]
Pete,

This is for a writer I see now.  I know 33id needs reader for this,which or at least something that fails gracefully when it comes across it, which is now in the reader.

John

On Jul 13, 2019 9:12 PM, Pete R Jemian <notifications@github.com> wrote:

@JPHammonds<https://github.com/JPHammonds> : this was for Christian Schleputz. I'd be interested to know who at 8ID say they use it. The code has not been usable for some years now. Now, the code is working, at least for the few valid test files in the repository.

**Comment by prjemian** [comment]
Is there anything now to be fixed?  The code now stops with a Python `spec2nexus.plugins.uxml.UXML_Error` if the scan's UXML does not validate with the `uxml.xsd` schema.  Should that be relaxed to just a reported warning without an exception?  Then, the writer proceeds to attempt writing with best efforts (might fail then due to problems).

**Comment by JPHammonds** [comment]
Just updated spec2nexus.  I am just using the reading functionality in rsMap3D & you had referenced writes.  Reading the first spec file that I picked works.  I even mangled one of the #UXML lines by removing a closing ‘>’ in one line.  The only issue that I found was that I now have to install pyRestTable.  I assume that this is needed by the writers.

John

**Comment by prjemian** [comment]
@JPHammonds emailed:
> Just updated spec2nexus. I am just using the reading functionality in rsMap3D & you had referenced writes. Reading the first spec file that I picked works. I even mangled one of the #UXML lines by removing a closing ‘>’ in one line. The only issue that I found was that I now have to install pyRestTable. I assume that this is needed by the writers. 

Thanks!
