### ISSUE TITLE
add plug-in support to add TIFF file from disk into HDF5 file

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#16]
SPEC data file should have the path to this file

**Comment by rayosborn** [comment]
Just thought I would mention that the tifffile module is now available on PyPI, if you are interested in making TIFF support a dependency.

**Comment by prjemian** [comment]
This issue is on hold until we get an example SPEC data file that calls for a TIFF image

**Comment by prjemian** [comment]
No further interest in 5 years, closing.  Open new issue if interest increases.
