### ISSUE TITLE
pyRestTable missing from package requirements

### ISSUE THREAD

**Issue by JPHammonds** [prjemian/spec2nexus#209]
When I install spec2nexus, which I use primarily for the spec reader in spec2nexus.spec, I get a ModuleNotFoundException for pyRestTable.  Since you include other requirements was wondering if this had been missed.

**Comment by prjemian** [comment]
Thanks.  Yes, it was missed.

**Comment by prjemian** [comment]
Released today in 1.1.6 for pip and conda installs
