### ISSUE TITLE
Index error reading a single scan SPEC file

### ISSUE THREAD

**Issue by rayosborn** [prjemian/spec2nexus#216]
I am trying to read a SPEC file generated by a SPEC macro at CHESS, which contains a single scan. I get the following traceback:
```
$ spec2nexus scan.spec 
reading SPEC data file: scan.spec
Traceback (most recent call last):
  File "/Users/rosborn/miniconda3/envs/py38/bin/spec2nexus", line 8, in <module>
    sys.exit(main())
  File "/Users/rosborn/miniconda3/envs/py38/lib/python3.8/site-packages/spec2nexus/nexus.py", line 189, in main
    out.save(nexus_output_file_name, scan_list)
  File "/Users/rosborn/miniconda3/envs/py38/lib/python3.8/site-packages/spec2nexus/writer.py", line 89, in save
    self.save_scan(nxentry, self.spec.getScan(key))
  File "/Users/rosborn/miniconda3/envs/py38/lib/python3.8/site-packages/spec2nexus/writer.py", line 143, in save_scan
    scan.interpret()        # ensure interpretation is complete
  File "/Users/rosborn/miniconda3/envs/py38/lib/python3.8/site-packages/spec2nexus/spec.py", line 637, in interpret
    func(self)
  File "/Users/rosborn/miniconda3/envs/py38/lib/python3.8/site-packages/spec2nexus/plugins/spec_common.py", line 1049, in postprocess
    data_lines_postprocessing(scan)
  File "/Users/rosborn/miniconda3/envs/py38/lib/python3.8/site-packages/spec2nexus/plugins/spec_common.py", line 1443, in data_lines_postprocessing
    buf = scan._interpret_data_row(values)
  File "/Users/rosborn/miniconda3/envs/py38/lib/python3.8/site-packages/spec2nexus/spec.py", line 684, in _interpret_data_row
    buf[self.L[col]] = float(val)
IndexError: list index out of range
```
The output file gets created but only contains `/S1/definition`. I am running spec2nexus-2021.1.7 with Python 3.8 on Mac OS X v10.14.6. I am attaching the SPEC file (with `.txt` added to the extension so that Github accepted it).

[scan.spec.txt](https://github.com/prjemian/spec2nexus/files/3985926/scan.spec.txt)

**Comment by prjemian** [comment]
@rayosborn : Thanks for this report.  I'm building a test case for it now.  

First problem I see is an inconsistency in the data file, seven columns specified (`#N 7`) and seven data columns given but only six column labels defined (`#L EPOCH Phi CESR IC1 IC2 DIODE`):

```
#N 7
#L EPOCH Phi CESR IC1 IC2 DIODE
1.0232 6.1048 51127.0000 157861.0000 26694.0000 0.0000 39777.0000
2.0526 6.2078 51127.0000 158333.0000 33138.0000 0.0000 53174.0000
```

Perhaps *spec2nexus* should supply default names when the number of labels provided is less than the number of columns described by `#N`.  Agree?

**Comment by rayosborn** [comment]
I can forward that observation to the CHESS instrument scientist to see if he understands how that happened and whether it's fixable. If this is an issue with the macro, I'm not sure how spec2nexus should handle it, because there would be an ambiguity about which column has no label. Perhaps it would be best to raise an explicit exception when the number of columns doesn't match `#N`.

**Comment by prjemian** [comment]
From the [SPEC manual](https://certif.com/spec_manual/user_1_4_1.html):

> the #L line gives the names for each column, each name separated from the other by two spaces.

In the file supplied, a single white space separates the column labels.  With the two-space delimiter, SPEC allows for column labels with one embedded white space, such as "2 theta".  By this rule, *spec2nexus* identifies only one column label specified in this file: `EPOCH Phi CESR IC1 IC2 DIODE`.  This is the reason for the `IndexError`, columns 2-7 have no corresponding labels.

**Comment by prjemian** [comment]
So, this fail will fail to parse with this exception:

```
  File "/home/mintadmin/Documents/eclipse/spec2nexus/src/spec2nexus/plugins/spec_common.py", line 1411, in data_lines_postprocessing
    len(scan.L), scan.N[0]
ValueError: # of given column labels in #L (1) does not match # specified in #N (7)
```

Agree?

**Comment by prjemian** [comment]
This data file has problems which were not identified clearly until this issue.  All problems are related to incorrect formatting  of the `#L` line.  The number of columns specified in #N matches the number of values on each data line (7).

1. The number of columns specified in #N does not match the number of columns described in #L
2. The labels given on #L are only delimited by single spaces.  This results in only one label defined.
3. The number of separate labels given in #L (6) does not equal the number of data columns.

**Comment by prjemian** [comment]
Perhaps a second exception should be raised when `len(scan.L) == 1` but `scan.L[0].split(" ") != scan.N[0]`.  That will address items 2 & 3 in previous comment.

**Comment by prjemian** [comment]
2. test: `len(scan.L) == 1 and scan.L[0].split(" ") == scan.N[0]`

This test should come first.  Test for 3. should be separate.

**Comment by prjemian** [comment]
One other test data file is affected by this change (incorrect `#N` line was uncovered).

**Comment by rayosborn** [comment]
All your suggestions look good to me. I've passed the link to this issue to the instrument scientist so he can comment if he wants to. It's a long time since I wrote a SPEC macro, but I'm a little surprised that SPEC doesn't generate the `#L` line automatically from a predefined list of variables. The issue seems to suggest that it is written explicitly by the macro as a formatted string.

**Comment by prjemian** [comment]
@rayosborn : There is enough evidence to support your suggestion that this file was not written by the unmodified SPEC standard macros.  For example, the standard macros place the scanned motor in the first column, here it is in the second column.  This file defines `EPOCH` as the first data column and uses floating-point precision.  Also, the label is `Epoch` when the standard macros are used and record such values with integer precision.  While a data column label is missing, it is not the scanned axis `phi` as the `#S` line suggests.  Since the macro was `fastsweep`, it is expected that some customization was likely.
