### ISSUE TITLE
#UE records

### ISSUE THREAD

**Issue by rayosborn** [prjemian/spec2nexus#29]
I have an example of a SPEC file written on APS Sector 6-ID-D, which triggers the following error when it is opened as a SpecDataFile:

    Traceback (most recent call last):
      File "/Users/rosborn/Documents/Computing/Repositories/nexpy/src/nexpy/readers/readspec.py", line 82, in choose_file
        self.spec = SpecDataFile(self.get_filename())
      File "/Users/rosborn/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/spec2nexus/prjPySpec.py", line 205, in __init__
        self.read()
      File "/Users/rosborn/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/spec2nexus/prjPySpec.py", line 241, in read
        scan = SpecDataFileScan(self.headers[-1], part)
      File "/Users/rosborn/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/spec2nexus/prjPySpec.py", line 360, in __init__
        self.interpret()
      File "/Users/rosborn/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/spec2nexus/prjPySpec.py", line 407, in interpret
        self.U[subkey] = strip_first_word(line)
    AttributeError: 'SpecDataFileScan' object has no attribute 'U'

The offending record is at the start of the following:

    #UE 100.339 0.123565 179.998 42.1688 (Energy in keV, Lambda in Angstroem, Undulator Gap + Energy)
    #X 0 -273.15 (Temperature Setpoint in K and C) 
    #UX 0 0 1 100.339 (All Banks: Filter, Thickness in mm, Transmission, calculated for energy)
    #UX1 0 0 1 0 (Bank 1:Filter, Thickness in mm, Transmission, calculated for energy)
    #UX2 0 0 1 0 (Bank 2:Filter, Thickness in mm, Transmission, calculated for energy)
    #UB 4.07999 -6.86533e-16 -6.56121e-16 -3.04118e-17 -4.07999 2.49819e-16 0 0 -4.07999
    #N 25

I'll post some more complete text in the next comment.

**Comment by rayosborn** [comment]
#F ~/data/run13_3/osborn/osborn.dat
#E 1383072022
#D Tue Oct 29 13:40:22 2013
#C psic6IDD  User = user6idd
#O0    Delta       Eta       Chi       Phi        Nu        Mu      tt_y      tt_z
#O1    m1_om    m1_chi    m1_phi     m2_om    m2_chi    m2_phi  m1_filter     mot43
#O2  m1_bend   m2_bend      m1_x      m1_y      m2_z        xs        zs        ys
#O3      tta       oma      chia      phia        xm        ym        xd        yd
#O4    sl1_t     sl1_b     sl1_o     sl1_i     sl2_t     sl2_b     sl2_o     sl2_i
#O5    sl4_t     sl4_b     sl4_o     sl4_i     sl5_t     sl5_b     sl5_o     sl5_i
#O6    sl3_t     sl3_b     sl3_o     sl3_i     sl3_r     dummy     aux_y  aux_x_base
#O7   aux_th     aux_x  x_detector  

#S 1  rotscan testing dummy 0 0 100 0.1 5
#D Tue Oct 29 14:05:53 2013
#T 0.1  (Seconds)
#G0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0
#G1 1.54 1.54 1.54 90 90 90 4.079990459 4.079990459 4.079990459 90 90 90 1 0 0 0 1 0 60 30 0 0 0 0 60 30 0 -90 0 0 1.54 1.54
#G3 4.079990459 -6.865325574e-16 -6.561207576e-16 -3.041179982e-17 -4.079990459 2.49819112e-16 0 0 -4.079990459
#G4 0 0 0 0.1235653136 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -180 -180 -180 -180 -180 -180 -180 -180 -180 0 0 0 0 0 0 0 0 0 0 0 0
#Q 0 0 0
#P0 0 0 90 -3 0 0 700 700
#P1 2.162381 -0.12024 -0.909126 2.162131 -0.80976 -0.799578 86.365625 0
#P2 -5.99 -5.99 1 4.6500032 2.8633327e-05 0 0 0
#P3 0 0 0 0 0 -3.5 0 0
#P4 0.25 -0.25 0.25 -0.25 0.35 -0.35 0.35 -0.35
#P5 2 -2 2 -2 2.84 -1.16 0.845 -3.155
#P6 0 -5 0 0 0 0 0 -21.95
#P7 0 21.74875 0 
#UE 100.339 0.123565 179.998 42.1688 (Energy in keV, Lambda in Angstroem, Undulator Gap + Energy)
#X 0 -273.15 (Temperature Setpoint in K and C) 
#UX 0 0 1 100.339 (All Banks: Filter, Thickness in mm, Transmission, calculated for energy)
#UX1 0 0 1 0 (Bank 1:Filter, Thickness in mm, Transmission, calculated for energy)
#UX2 0 0 1 0 (Bank 2:Filter, Thickness in mm, Transmission, calculated for energy)
#UB 4.07999 -6.86533e-16 -6.56121e-16 -3.04118e-17 -4.07999 2.49819e-16 0 0 -4.07999
#N 25
#L dummy  Time  DelTime  Index  Dropped  H  K  L  DegK_reg  DegK_sample  Epoch  Seconds  RingCurrent  moa  mob  coa  cob  MCA_Detector  MCA_Total  AD_ROI1_Total  AD_ROI1_Max  scu0_cur  MCA_Compton  Monitor  Detector
#C Tue Oct 29 14:05:53 2013.  Scan aborted after 0 points.

#S 2  rotscan testing dummy 0 0 100 0.1 5
#D Tue Oct 29 14:06:25 2013
#T 0.1  (Seconds)
#G0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0
#G1 1.54 1.54 1.54 90 90 90 4.079990459 4.079990459 4.079990459 90 90 90 1 0 0 0 1 0 60 30 0 0 0 0 60 30 0 -90 0 0 1.54 1.54
#G3 4.079990459 -6.865325574e-16 -6.561207576e-16 -3.041179982e-17 -4.079990459 2.49819112e-16 0 0 -4.079990459
#G4 0 0 0 0.1235653136 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -180 -180 -180 -180 -180 -180 -180 -180 -180 0 0 0 0 0 0 0 0 0 0 0 0
#Q 0 0 0
#P0 0 0 90 -3 0 0 700 700
#P1 2.162381 -0.12024 -0.909126 2.162131 -0.80976 -0.799578 86.365625 0
#P2 -5.99 -5.99 1 4.6500032 2.8633327e-05 0 0 0
#P3 0 0 0 0 0 -3.5 0 0
#P4 0.25 -0.25 0.25 -0.25 0.35 -0.35 0.35 -0.35
#P5 2 -2 2 -2 2.84 -1.16 0.845 -3.155
#P6 0 -5 0 0 0 0 0 -21.95
#P7 0 21.74875 0 
#UE 100.339 0.123565 179.998 42.1688 (Energy in keV, Lambda in Angstroem, Undulator Gap + Energy)
#X 0 -273.15 (Temperature Setpoint in K and C) 
#UX 0 0 1 100.339 (All Banks: Filter, Thickness in mm, Transmission, calculated for energy)
#UX1 0 0 1 0 (Bank 1:Filter, Thickness in mm, Transmission, calculated for energy)
#UX2 0 0 1 0 (Bank 2:Filter, Thickness in mm, Transmission, calculated for energy)
#UB 4.07999 -6.86533e-16 -6.56121e-16 -3.04118e-17 -4.07999 2.49819e-16 0 0 -4.07999
#N 25
#L dummy  Time  DelTime  Index  Dropped  H  K  L  DegK_reg  DegK_sample  Epoch  Seconds  RingCurrent  moa  mob  coa  cob  MCA_Detector  MCA_Total  AD_ROI1_Total  AD_ROI1_Max  scu0_cur  MCA_Compton  Monitor  Detector
0 1383073585.374759 -0.000759 2 0          0          0          0 0 0 1563 0.1 0.0102 1 1 1 1 141 11699 0 0 0 3848 1 0
0 1383073585.578769 -0.000769 4 0          0          0          0 0 0 1563 0.1 0.0102 1 1 1 1 141 11699 0 0 0 3848 1 0
0 1383073585.703298 -0.000298 5 0          0          0          0 0 0 1563 0.1 0.0102 1 1 1 1 141 11699 0 0 0 3848 1 0
0 1383073585.889650 -0.000650 7 0          0          0          0 0 0 1563 0.1 0.0102 1 1 1 1 141 11699 0 0 0.12207404 3848 1 0
0 1383073586.028877 0.000123 8 0          0          0          0 0 0 1564 0.1 0.0102 1 1 1 1 141 11699 0 0 0.12207404 3848 1 0
0 1383073586.242838 -0.000838 10 0          0          0          0 0 0 1564 0.1 0.0102 1 1 1 1 141 11699 0 0 0.12207404 3848 1 0
0 1383073586.401895 0.000105 12 0          0          0          0 0 0 1564 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.12207404 3848 1 0
0 1383073586.617823 0.000177 14 0          0          0          0 0 0 1564 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.12207404 3848 1 0
0 1383073586.773157 -0.000157 15 0          0          0          0 0 0 1564 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.12207404 3848 1 0
0 1383073586.987346 -0.000346 18 0          0          0          0 0 0 1565 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.12207404 3848 1 0
0 1383073587.111611 -0.000611 19 0          0          0          0 0 0 1565 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.12207404 3848 1 0
0 1383073587.235586 -0.000586 20 0          0          0          0 0 0 1565 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.12207404 3848 1 0
0 1383073587.396767 0.000233 22 0          0          0          0 0 0 1565 0.1 0.0102 1 1 1 1 141 11699 0 0 0.15259255 3848 1 0
0 1383073587.558454 -0.000454 23 0          0          0          0 0 0 1565 0.1 0.0102 1 1 1 1 141 11699 0 0 0.15259255 3848 1 0
0 1383073587.773534 -0.000534 26 0          0          0          0 0 0 1565 0.1 0.0102 1 1 1 1 141 11699 0 0 0.15259255 3848 1 0
0 1383073587.949097 -0.000097 27 0          0          0          0 0 0 1566 0.1 0.0102 1 1 1 1 141 11699 0 0 0.15259255 3848 1 0
0 1383073588.158376 -0.000376 29 0          0          0          0 0 0 1566 0.1 0.0102 1 1 1 1 141 11699 0 0 0.15259255 3848 1 0
0 1383073588.327235 -0.000235 31 0          0          0          0 0 0 1566 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.091555528 3848 1 0
0 1383073588.532477 -0.000477 33 0          0          0          0 0 0 1566 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.091555528 3848 1 0
0 1383073588.679982 0.000018 35 0          0          0          0 0 0 1566 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.091555528 3848 1 0
0 1383073588.888847 0.000153 37 0          0          0          0 0 0 1566 0.1 0.0102 1 1 1 1 141 11699 0 0 0.030518509 3848 1 0
0 1383073589.070463 -0.000463 38 0          0          0          0 0 0 1567 0.1 0.0102 1 1 1 1 141 11699 0 0 0.030518509 3848 1 0
0 1383073589.282489 -0.000489 41 0          0          0          0 0 0 1567 0.1 0.0102 1 1 1 1 141 11699 0 0 0.030518509 3848 1 0
0 1383073589.439304 -0.000304 42 0          0          0          0 0 0 1567 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.18311106 3848 1 0
0 1383073589.657698 -0.000698 44 0          0          0          0 0 0 1567 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.18311106 3848 1 0
0 1383073589.822744 -0.000744 46 0          0          0          0 0 0 1567 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.061037019 3848 1 0
0 1383073590.036854 0.000146 48 0          0          0          0 0 0 1568 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.061037019 3848 1 0
0 1383073590.195998 0.000002 50 2          0          0          0 0 0 1568 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.061037019 3848 1 0
0 1383073590.403124 -0.000124 52 4          0          0          0 0 0 1568 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.45777764 3848 1 0
0 1383073590.561602 -0.000602 53 4          0          0          0 0 0 1568 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.45777764 3848 1 0
0 1383073590.774385 -0.000385 55 7          0          0          0 0 0 1568 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.45777764 3848 1 0
0 1383073590.937098 -0.000098 57 8          0          0          0 0 0 1568 0.1 0.0102 1 1 1 1 141 11699 0 0 0.030518509 3848 1 0
0 1383073591.382668 -0.000668 62 12          0          0          0 0 0 1569 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.21362957 3848 1 0
0 1383073591.546547 -0.000547 63 13          0          0          0 0 0 1569 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.21362957 3848 1 0
0 1383073591.761622 -0.000622 65 15          0          0          0 0 0 1569 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.21362957 3848 1 0
0 1383073591.923105 -0.000105 67 16          0          0          0 0 0 1570 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.061037019 3848 1 0
0 1383073592.134837 0.000163 69 18          0          0          0 0 0 1570 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.061037019 3848 1 0
0 1383073592.306965 0.000035 71 21          0          0          0 0 0 1570 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.061037019 3848 1 0
0 1383073592.504328 -0.000328 73 23          0          0          0 0 0 1570 0.1 0.0102 1 1 1 1 141 11699 0 0 0.061037019 3848 1 0
0 1383073592.666886 0.000114 74 23          0          0          0 0 0 1570 0.1 0.0102 1 1 1 1 141 11699 0 0 0.061037019 3848 1 0
0 1383073592.875718 0.000282 76 25          0          0          0 0 0 1570 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.15259255 3848 1 0
0 1383073593.034075 -0.000075 78 26          0          0          0 0 0 1571 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.15259255 3848 1 0
0 1383073593.245451 -0.000451 80 29          0          0          0 0 0 1571 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.15259255 3848 1 0
0 1383073593.418504 -0.000504 82 32          0          0          0 0 0 1571 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.30518509 3848 1 0
0 1383073593.634928 0.000072 84 34          0          0          0 0 0 1571 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.30518509 3848 1 0
0 1383073593.795867 0.000133 86 36          0          0          0 0 0 1571 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.30518509 3848 1 0
0 1383073594.005156 -0.000156 88 38          0          0          0 0 0 1572 0.1 0.0102 1 1 1 1 141 11699 0 0 0.061037019 3848 1 0
0 1383073594.160503 -0.000503 89 38          0          0          0 0 0 1572 0.1 0.0102 1 1 1 1 141 11699 0 0 0.061037019 3848 1 0
0 1383073594.375008 -0.000008 91 41          0          0          0 0 0 1572 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.091555528 3848 1 0
0 1383073594.528036 -0.000036 93 42          0          0          0 0 0 1572 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.091555528 3848 1 0
0 1383073594.737089 -0.000089 95 45          0          0          0 0 0 1572 0.1 0.0102 1 1 1 1 141 11699 0 0 -0.091555528 3848 1 0
0 1383073594.908258 -0.000258 97 48          0          0          0 0 0 1573 0.1 0.0102 1 1 1 1 141 11699 0 0 0.18311106 3848 1 0
0 1383073595.126488 -0.000488 99 50          0          0          0 0 0 1573 0.1 0.0102 1 1 1 1 141 11699 0 0 0.18311106 3848 1 0
0 1383073595.267593 -0.000593 100 51          0          0          0 0 0 1573 0.1 0.0102 1 1 1 1 141 11699 0 0 0.18311106 3848 1 0
0 1383073595.478344 -0.000344 102 52          0          0          0 0 0 1573 0.1 0.0102 1 1 1 1 141 11699 0 0 0 3848 1 0
#R 2 1 0 0 0 0 55 1573.56 0 (scan nr., Y_PEAK, at pos., FWHM, at pos., COM, SUM, Time, TEMP_CS)

**Comment by prjemian** [comment]
Which version of spec2nexus are you running?

**Comment by prjemian** [comment]
with version 2015.0113.0, no errors are reported for the custom data lines (#UE, #UX, ...) but a different exception is reported and the resulting data file is not written correctly:

PS C:\Users\Pete\Desktop> spec2nexus.exe .\osborn.dat
reading SPEC data file: .\osborn.dat
Traceback (most recent call last):
  File "C:\Users\Pete\Apps\Anaconda\Scripts\spec2nexus-script.py", line 9, in <module>
    load_entry_point('spec2nexus==2015.0113.0', 'console_scripts', 'spec2nexus')()
  File "C:\Users\Pete\Apps\Anaconda\lib\site-packages\spec2nexus\nexus.py", line 185, in main
    out.save(nexus_output_file_name, scan_list)
  File "C:\Users\Pete\Apps\Anaconda\lib\site-packages\spec2nexus\writer.py", line 78, in save
    self.save_scan(nxentry, self.spec.getScan(key))
  File "C:\Users\Pete\Apps\Anaconda\lib\site-packages\spec2nexus\writer.py", line 106, in save_scan
    scan.interpret()        # ensure interpretation is complete
  File "C:\Users\Pete\Apps\Anaconda\lib\site-packages\spec2nexus\spec.py", line 453, in interpret
    func(self)
  File "C:\Users\Pete\Apps\Anaconda\lib\site-packages\spec2nexus\plugins\spec_common_spec2nexus.py", line 692, in postprocess
    data_lines_postprocessing(scan)
  File "C:\Users\Pete\Apps\Anaconda\lib\site-packages\spec2nexus\plugins\spec_common_spec2nexus.py", line 998, in data_lines_postprocessing
    buf = scan._interpret_data_row(values)
  File "C:\Users\Pete\Apps\Anaconda\lib\site-packages\spec2nexus\spec.py", line 484, in _interpret_data_row
    label = self.L[col]
IndexError: list index out of range

**Comment by prjemian** [comment]
PS C:\Users\Pete\Desktop> spec2nexus.exe -v
2015.0113.0

**Comment by rayosborn** [comment]
Sorry about that - elementary mistake. I thought I had installed the latest version, but my version of NeXpy was obviously still running an old version. I just did a pip install spec2nexus --upgrade, which must have somehow worked because the new version (2015.0113.0) seems to read it without problem. The upgrade didn't complete though, because it attempted to update h5py, and couldn't install Cython. Not your problem though.

**Comment by prjemian** [comment]
pip update --no-deps spec2nexus

**Comment by prjemian** [comment]
This file from APS 6-ID-D has a pathological error.

The #L line in SPEC uses a double-space (or more) separator between 
labels so as to allow multiword labels to use a single space separator. 
  Such as this example which describes three column labels:

#L two theta  I00  counts

It seems there is a local SPEC macro override that rewrites how the #L 
line is written to the file.

It is possible to change how spec2nexus interprets the #L line but that 
would cause greater disruption to the many files which relay on a 
double-space to separate column labels.

To read this file with spec2nexus, a custom control line handler plugin 
should be written.  The custom plugin should copy the existing class

   class SPEC_Labels(ControlLineHandler):

from <spec2nexus>/plugins/spec_common_spec2nexus.py and modify this line:

         # Some folks use more than two spaces!  Use regular 
expression(re) module
         scan.L = re.split("  +", strip_first_word(text))

to fit the situation.

Another possibility is for spec2nexus to develop a list of #L handlers 
to try, in succession, for this rare but obvious pathology.

Pete

**Comment by rayosborn** [comment]
Thanks for the information. I'll have to ask Guy Jennings if he knows why the L record is written incorrectly. I think he wrote the relevant Spec macro.

**Comment by prjemian** [comment]
A possibility is that the spaces were removed during various file handling while emailing, wiki, issue report, ...  

I've built a second try handler for it that test for when len(#L) == 1 and #N[0] > 1, that works and satisfies the "tolerant acceptor" policy.  See https://github.com/prjemian/spec2nexus/issues/30
