### ISSUE TITLE
Syntax compatibility issue in plugin file "spec_common.py" when using Python 3.6 (potentially Python <3.8)

### ISSUE THREAD

**Issue by wilsonlabucsb** [prjemian/spec2nexus#304]
Using spec2nexus==2021.2.6 and python==3.6.10

Received the following error:

```
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "test_script.py", line 45, in <module>
    spexus = SpecDataFile(specfile)
  File "C:\...\...\...\...\...\lib\site-packages\spec2nexus\spec.py", line 249, in __init__
    self.read()
  File "C:\...\...\...\...\...\lib\site-packages\spec2nexus\spec.py", line 446, in read
    from .control_lines import control_line_registry
  File "C:\...\...\...\...\...\lib\site-packages\spec2nexus\control_lines.py", line 87, in <module>
    control_line_registry = ControlLines()  # singleton
  File "C:\...\...\...\...\...\lib\site-packages\spec2nexus\control_lines.py", line 32, in __init__
    install_user_plugin(plugin_file)
  File "C:\...\...\...\...\...\lib\site-packages\spec2nexus\plugin_core.py", line 47, in install_user_plugin
    spec.loader.exec_module(module)
  File "<fstring>", line 1
    (scan.L=)
           ^
SyntaxError: invalid syntax
```

Fixed the issue by modifying the following line in ...\lib\site-packages\spec2nexus\plugins\spec_common.py > `data_lines_postprocessing()`:

    if len(scan.L) != scan.N[0]:
        # https://github.com/prjemian/spec2nexus/issues/216
        # https://github.com/prjemian/spec2nexus/issues/300
        warnings.warn(
            f"file {scan.specFile}: "
            f"#S {scan.S}: "
            f"# of given column labels in #L ({len(scan.L)}) "
            f"does not match # specified in #N ({scan.N[0]})"
            f": {scan.L=}"
        )

---------->

    if len(scan.L) != scan.N[0]:
        # https://github.com/prjemian/spec2nexus/issues/216
        # https://github.com/prjemian/spec2nexus/issues/300
        warnings.warn(
            f"file {scan.specFile}: "
            f"#S {scan.S}: "
            f"# of given column labels in #L ({len(scan.L)}) "
            f"does not match # specified in #N ({scan.N[0]})"
            f": {scan.L}"
        )

Some info from ChatGPT: 
`scan.L=`: The equal sign = is used in the f-string expression to include both the variable name (scan.L) and its value in the resulting string. It's a shorthand syntax introduced in Python 3.8 (PEP 572) for including variable names and their values in f-strings.

**Comment by prjemian** [comment]
Thanks for the report, @wilsonlabucsb.  This is completely expected.  Support for Python for Python versions <3.8 was dropped in spec2nexus release [2021.2.4](https://github.com/prjemian/spec2nexus/blob/main/CHANGES.rst#202124).  Refer to this [chart](https://devguide.python.org/versions/#status-of-python-versions) for the status of Python versions.

**Comment by prjemian** [comment]
BTW, you've applied the correct fix for backwards compatibility of this line of code.  The f-strings came in Py3.6, the extra`=` syntax was added in Py3.8 and use of it is too addictive to avoid.

**Comment by prjemian** [comment]
The equivalent code would be: `f": scan.L={scan.L}"  (that's what the `=` syntax does).
