### ISSUE TITLE
Incorrect maximum scan number

### ISSUE THREAD

**Issue by rayosborn** [prjemian/spec2nexus#44]
The latest versions of spec2nexus returns scan numbers as a list of strings rather than integers. This seems to prevent the correct maximum scan number being identified in getMaxScanNumber. 

Here's a sample session:

    In [1]: import spec2nexus
    In [2]: spec2nexus.__version__
    Out[2]: '2015.1221.0'
    In [3]: spec=SpecDataFile('/Users/rosborn/Documents/Computing/NeXpy/NeXus Data/lmn40.spe')
    In [4]: print spec.getScanNumbers()
    Out[4]: ['216', '217', '214', '215', '212', '213', '210', '211', '165', '264', '265', '219', '133', '132', '131', '130', '137', '136', '135', '134', '139', '138', '166', '24', '25', '26', '27', '20', '21', '22', '23', '160', '28', '29', '161', '4', '8', '163', '119', '271', '258', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '269', '268', '167', '118', '59', '58', '55', '54', '57', '56', '51', '50', '53', '52', '259', '164', '201', '199', '179', '200', '195', '194', '197', '178', '191', '190', '193', '192', '115', '114', '88', '89', '111', '110', '113', '112', '82', '83', '80', '81', '86', '87', '84', '204', '251', '198', '256', '206', '226', '257', '3', '177', '254', '7', '247', '255', '225', '245', '244', '108', '109', '243', '242', '102', '100', '101', '106', '107', '104', '105', '39', '38', '33', '32', '31', '30', '37', '36', '35', '34', '246', '252', '205', '223', '176', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '175', '174', '173', '172', '171', '170', '203', '222', '181', '253', '248', '182', '183', '180', '2', '162', '187', '184', '6', '220', '186', '188', '189', '202', '196', '221', '185', '99', '98', '168', '229', '91', '90', '93', '92', '95', '94', '97', '96', '11', '10', '13', '12', '15', '14', '17', '16', '19', '18', '117', '250', '116', '151', '150', '153', '152', '155', '154', '157', '156', '159', '158', '234', '238', '239', '207', '235', '236', '237', '230', '231', '232', '233', '224', '48', '49', '46', '47', '44', '45', '42', '43', '40', '41', '1', '5', '9', '146', '147', '144', '145', '142', '143', '140', '141', '209', '148', '149', '77', '75', '74', '73', '72', '71', '70', '79', '78', '263', '249', '262', '227', '261', '270', '260', '267', '266']
    In [5]: spec.getMaxScanNumber()
    Out[5]: '99'

If strings are preferred, it would be good to do a natural sort on them, so that the scan list increases in numerical order.

**Comment by prjemian** [comment]
The test data file "CdOsO" has multiple instances of scan 1.  The fix should be tested with both this file and "lmne40.spe".

**Comment by prjemian** [comment]
When there are multiple scans with the same scan number (such as "CdOsO"), the scan numbers are written as str("%d.%d") % (scan_number, unique_index) and can be sorted if they are converted to float.

**Comment by prjemian** [comment]
This code (placed in spec.py) will test both files:

```
if __name__ == '__main__':
    for fn in ('lmn40.spe', 'CdOsO'):
        test_file = os.path.join('data', fn)
        sdf=SpecDataFile(test_file)
        print sdf.getScanNumbers()
        print sdf.getMinScanNumber()
        print sdf.getMaxScanNumber()
```

**Comment by rayosborn** [comment]
Just to confirm that it works for me. Thanks.
