### ISSUE TITLE
Pip and Conda installs are out of sync

### ISSUE THREAD

**Issue by JPHammonds** [prjemian/spec2nexus#49]
It appears that the PIP installer gives a newer version than Conda (anaconda) installer.  Something was apparently "fixed" that I needed between the two versions.

**Comment by prjemian** [comment]
*build the conda kit *after* pushing a new update to PyPI
*use conda skeleton pypi, here's the linux steps::

    cd /tmp
    conda skeleton pypi spec2nexus
    conda build spec2nexus
