### ISSUE TITLE
Interpret the #G lines for UB Matrix and other terms

### ISSUE THREAD

**Issue by JPHammonds** [prjemian/spec2nexus#51]
Users will appreciate this.  Since I am not familiar with the other uses of the G codes some others might fall out here. 

----

[added]

The `#Gn` lines encode numerical values in a very information dense form.  This content needs to be interpreted and assigned to meanings.  This is most important since the number of values in each line varies due to the diffractometer geometry in use.

**Comment by prjemian** [comment]
Exact meaning of the #G lines in the data files varies by the instrument geometry used.
The files do not name the geometry.  It may be possible to deduce the geometry from the specific combination of #G lines, the number of values in each, and the names of the first defined positioners (as required by the geometry).

From the SPEC manual:
"The next lines give information that describe the diffractometer conﬁguration at the start of the scan. Following #G0 are the current values of the four-circle parameters, which are deﬁned four-circle macro ﬁle, *macros/fourc.src*.Following #G1 are the current parameters describing the crystal lattice and orientation matrix. The identiﬁcation of these parameters is in the macro ﬁle *macros/ub.mac*."

**Comment by prjemian** [comment]
The real goal is for the spec2nexus.spec code to parse, label , and extract each of the values coded in the #G lines in the data file.

These from a fourc instrument:
```
#G0 3 0 1 0 0 1 0 0 0 0 0 0 50 0 0.1 0 68 68 50 -1 1 1 3.13542 3.13542 0 463.6 838.8
#G1 3.781726143 3.791444574 3.79890313 90.2546203 90.01815424 89.89967858 1.661462253 1.657219786 1.65396364 89.74541108 89.98229138 90.10024173 0 0 2 1 1 3 38.1245 19.2545 90.1385 0 0 0 65.571 32.79425 115.2755 46.1725 0 0 1.239424258 1.239424258
#G3 -1.661044167 0.04007351558 -0.0001588220447 -0.03726829786 -1.656705712 0.002513493361 0.0004106485684 0.009885210717 1.653961723
#G4 0.002845777681 0.0001823999657 1.999993054 1.239424258 19.03490858 19.04905116 0 85.05616026 0.7 0 0 0 0 0 0 0 -180 -180 -180 -180 -180 -180 -180 -180 -180 0
```

These are from APS USAXS:
```
#G0 0
#G1 0
#G3 0
#G4 0
```

These are from some instrument (geometry unknown to me) at APS 1ID:
```
#G0 0
#G1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
#G2 0
```

These are from psic at APS 33ID:
```
#G0 0 0 0 0 0 1 0 0 0 0 0 0 50 0 0 0 1 0 0 0 0
#G1 3.825 3.888 11.704 90 90 90 1.64266 1.61605 0.536841 90 90 90 0 0 12 1 0 11 90.2448 44.607 89.08 26.8835 0.002 0 84.7493 43.836 73.67 26.8035 0.002 0 1.38221 1.38098
#G2 0
```

**Comment by prjemian** [comment]
Feb 29 email thread:

Asked [SPEC developer] about deducing the geometry from the scan file. 
He provided some good information as well as suggesting this might 
be a good thing to add as a line to the header.

**Comment by prjemian** [comment]
from standard.mac

      #G0 ...	       geometry parameters from G[] array (geo mode, sector, etc)
      #G1 ...	       geometry parameters from U[] array (lattice constants, orientation reflections)
      # 	       G2 is unused
      #G3 ...	       geometry parameters from UB[] array (orientation matrix)
      #G4 ...	       geometry parameters from Q[] array (lambda, frozen angles, cut points, etc)

**Comment by prjemian** [comment]
#G3 is always 9 values, the orientation matrix

**Comment by prjemian** [comment]
So, on best efforts, we guess, guided by the lookup table above.  Sounds like a dictionary of diffractometer, geo_terms where geo_terms is a dictionary with keys G0, G3, G4 and values [names of terms].

G1 is either 1 value (0) or *a b c alpha beta gamma* + 26 terms for the reflections

**Comment by prjemian** [comment]
APS 30ID HERIX

```
#G0 0 0 1 1 1 0 0 0 0 0 0 0 50 0 0.1 0 68 68 50 -1 1 1 3.13542 3.13542 0 463.6 838.8
#G1 3.90529338 3.90529338 3.90529338 90 90 90 1.608889447 1.608889447 1.608889447 90 90 90 2 2 1 1 1 0 23.1567 11.5845 -11.96625 -0.38 0 0 10.8606 5.4305 7.59375 0 0 0 0.52262 0.52262 0 0
#G3 1.130782382 1.125057736 0.2100036862 1.137418885 -1.137480834 -0.03067385977 0.1270225902 0.1700226323 -1.594830028
#G4 0.4125729195 0.445923122 0.08039922851 0.52262 0.001559967413 4.658126097 0 -72.71464805 0 0 0 0 0.05 0 0 0 -180 -180 -180 -180 -180 -180 -180 -180 -180 0
```

**Comment by prjemian** [comment]
G1 decoded

| G1 | term | meaning |
| -- | -- | -- |
| 0 | a | a lattice constant (real space) |
| 1 | b | b lattice constant (real space) |
| 2 | c | c lattice constant (real space) |
| 3 | alpha | alpha lattice angle (real space) |
| 4 | beta | beta  lattice angle (real space) |
| 5 | gamma | gamma lattice angle (real space) |
| 6 | a_hkl | a lattice constant (reciprocal space) |
| 7 | b_hkl | b lattice constant (reciprocal space) |
| 8 | c_hkl | c lattice constant (reciprocal space) |
| 9 | alpha_hkl | alpha lattice angle (reciprocal space) |
| 10 | beta_hkl | beta  lattice angle (reciprocal space) |
| 11 | gamma_hkl | gamma lattice angle (reciprocal space) |
| 12 | H_or0 | H of primary reflection |
| 13 | K_or0 | K of primary reflection |
| 14 | L_or0 | L of primary reflection |
| 15 | H_or1 | H of secondary reflection |
| 16 | K_or1 | K of secondary reflection |
| 17 | L_or1 | L of secondary reflection |
| 18 | u00 | reflection u0, angle 0 |
| 19 | u01 | reflection u0, angle 1 |
| 20 | u02 | reflection u0, angle 2 |
| 21 | u03 | reflection u0, angle 3 |
| 22 | u04 | reflection u0, angle 4 |
| 23 | u05 | reflection u0, angle 5 |
| 24 | u10 | reflection u1, angle 0 |
| 25 | u11 | reflection u1, angle 1 |
| 26 | u12 | reflection u1, angle 2 |
| 27 | u13 | reflection u1, angle 3 |
| 28 | u14 | reflection u1, angle 4 |
| 29 | u15 | reflection u1, angle 5 |
| 30 | lambda0 | lambda for or0 |
| 31 | lambda1 | lambda for or1 |
| 32 | u06 | reflection u0, angle 6 (optional) |
| 33 | u16 | reflection u1, angle 6 (optional) |

**Comment by prjemian** [comment]
G3 is UB (orientation) matrix: `ub00 ub01 ub02 ub10 ub11 ub12 ub20 ub21 ub22`

| | UB_0 | UB_1 | UB_2 |
| -- | -- | -- | -- |
| 0 | G3[0] | G3[1] | G3[2] |
| 1 | G3[3] | G3[4] | G3[5] |
| 2 | G3[6] | G3[7] | G3[8] |

**Comment by prjemian** [comment]
Additional technique to deduce diffractometer geometry is to examine the first *n* motor mnemonics, the diffractometer principle motor axes.  One technique is described in *macros/fourc.src*.  Other geometries have different techniques.

**Comment by prjemian** [comment]
Some geometries have variants, such as *fourc*.  Check that these variants are only in the context of motors (names and numgeo).

**Comment by prjemian** [comment]
Variations would each be described by name (the key) and a move of motors and numgeo as a dictionary

#### Now

    'geometry_name': {
        'motors': []
        'numgeo': int
        'variants': bool
        ...

#### Proposed

    'geometry_name': {
        'variations': {
            'standard': ["motor", "names"],
            'alternative1': ["other", "motor", "names"],
        }
        ...

numgeo would be computed as the length of the variation list

**Comment by prjemian** [comment]
Does not capture the complexity.  Some motors are in expected positions, other motors must be present (for say the *3axis* variation of *fourc*).

**Comment by prjemian** [comment]
This structure captures the complexity:

```
 'fourc': {'G': [...],
           'Q': [...],
           'modes': [...],
           'variations': {
           		'standard': {
           		    'motors': ['tth', 'th', 'chi', 'phi'],
           		    'other-motors': []
           		},
           		'omega': {
           		    'motors': ['tth', 'om', 'chi', 'phi'],
           		    'other-motors': []
           		},
           		'kappa': {
           		    'motors': ['tth', 'om', 'chi', 'phi', 'kth', 'kap', 'kphi'],
           		    'other-motors': []
           		},
           		'xtalogic': {
           		    'motors': ['tth', 'om', 'chi', 'phi', 'kth', 'kap', 'kphi'],
           		    'other-motors': ['xlhgt',]
           		},
           		'picker': {
           		    'motors': ['tth', 'th', 'chi', 'phi'],
           		    'other-motors': ['chiR', 'phiR']
           		},
           		'3axis': {
           		    'motors': ['tth', 'th', 'chi', 'phi'],
           		    'other-motors': ['thR', 'tthR', 'sy', 'ay', 'dy', 'mth', 'ath']
           		}
           }
           },
```

**Comment by prjemian** [comment]
In this recent structure, `motors` are the first motors defined in the motors array while `other-motors` can be any place (other than first) in the motors array.

**Comment by prjemian** [comment]
Here's the code that did the initial parsing:

<details>
<summary><tt>parse.py</tt></summary>
<p>

```

"""
parse SPEC geometry specifications for spec2nexus
"""

import os, sys, pprint, json

def main():
    path = os.path.dirname(__file__)
    geometries = {}

    for filename in os.listdir(path):
        if not filename.endswith(".src"):
            continue
        with open(filename, "r") as fp:
            buf = fp.read()

        geo_name = filename.split(".")[0]
        structure = dict(numgeo=0, motors=[], G=[], Q=[], modes=[], variants=False)
        geometries[geo_name] = structure
        
        if buf.find("no_hkl")>= 0:
            print(f"file: {filename}  no HKL")
            continue
        
        in_assign = False
        in_gmodes = False
        numgeo = 0
        motors = []
        G = []
        Q = []
        modes = []
        variants = False

        for line in buf.splitlines():
            line = line.strip()
            if line.startswith("def _assign"):
                in_assign = True
            elif line.startswith("_assign"):
                in_assign = False
            elif in_assign and line.startswith("_numgeo"):
                numgeo = int(line.split()[-1])
            elif in_assign and line.startswith("mA[") and line.find("=") > 0:
                motors.append(line.split("=")[-1].strip())
            elif not in_assign and not in_gmodes and line.startswith("constant gmodes"):
                in_gmodes = True
            elif in_gmodes:
                if geo_name == "sixc" and len(modes) == 12:
                    p = 5
                p = line.find(":")
                _s = line[p+1:].strip('"], ')
                modes.append(_s)
                if line.endswith("]"):
                    in_gmodes = False
            elif not in_assign and line.startswith("def ") and line.find("]'") > 0:
                for key in "G Q".split():
                    s = f"'{key}["
                    if line.find(s) > 0:
                        try:
                            define, comment = line.split("#")
                        except ValueError:
                            define, comment = line, ""
                        v = (define.split()[1].strip(), comment.strip())
                        if key == "G":
                            G.append(v)
                        else:
                            Q.append(v)

        # assert numgeo == len(motors)
        variants = numgeo != len(motors)
        print(f"geometry:{geo_name}  ok:{variants}  numgeo={numgeo}, motors:{motors}  G={G}  Q={Q}")
        structure["numgeo"] = numgeo
        structure["motors"] = motors
        structure["G"] = G
        structure["Q"] = Q
        structure["modes"] = modes
        structure["variants"] = variants
    
    pprint.pprint(geometries)
#     print(json.dumps(geometries, indent=2))


if __name__ == "__main__":
    main()
```

</p>
</details>

**Comment by prjemian** [comment]
The existing `geometries.txt` file will take manual editing to refactor to this new structure.

**Comment by prjemian** [comment]
Next, convert the dictionary in `geometries.txt` to Python classes.

**Comment by prjemian** [comment]
When order is important (in the `diffractometer-geometries.dict` file), such as designating a default, use [dict] rather than {key: dict}.

**Comment by prjemian** [comment]
Need U[] terms for each geometry.

**Comment by prjemian** [comment]
Now, time to add to the #Gn control line handler plugin
