### ISSUE TITLE
Release 2016.0601.0 cannot handle MCAs from spec data files

### ISSUE THREAD

**Issue by Henry0422** [prjemian/spec2nexus#55]
I realized latest release 2016.0601.0 cannot handle our spec data files with MCAs. 

When I installed latest spec2nexus release (version 2016.0601.0) , somehow, the package didn’t contain the essential component to convert MCAs. When I was using release 2016.0601.0 to convert `.dat` to `hdf5`, the hdf5 file didn't get all the related MCAs data from the spec data file.

I just reinstalled previous spec2nexus release (version 2016.0216.0)  on Windows laptop. After converting, the hdf5 file contains MCAs data.

I wonder to know if you guys missed something or removed something by accident? I appreciate if someone could help me look into this.

Thank you,

Henry

**Comment by prjemian** [comment]
With the 2016.0601.0 release, the regular expression used to match the key on each SPEC line was expanded to match the entire key, rather than some part of it.  This was discovered with support for our XPCS instrument (uses #XPCS lines which matched against the standard #X macro for temperature support).

Likely your data files were caught up in this.  Apologies.

Can you send me an example of your SPEC file with MCA data?
Improving support for MCA data is a TODO item.  Need more example data files.

Have you tried running spec2nexus on the example data file ``33id_spec.dat`` included with the distribution?  Scan 1 has MCA data (all zeroes).  This data does show up in the .hdf5 file when I run it.  Here's an example console session using Windows Powershell:

	PS D:\temp> spec2nexus -v
	2016.0601.0
	PS C:\Users\Pete> copy D:\Apps\Anaconda\Lib\site-packages\spec2nexus\data\33id_spec.dat d:\temp\
	PS C:\Users\Pete> cd d:\temp
	PS D:\temp> dir


		Directory: D:\temp


	Mode                LastWriteTime         Length Name
	----                -------------         ------ ----
	-a----        2/19/2016   4:15 PM        1316799 33id_spec.dat


	PS D:\temp> h5toText .\33id_spec.hdf5
	.\33id_spec.hdf5
	  @SPEC_date = 2003-07-17T02:37:32
	  @SPEC_file = samplecheck_7_17_03
	  @SPEC_epoch = 1058427452
	  @SPEC_user = epix
	  @spec2nexus_version = 2016.0601.0
	  @h5py_version = 2.5.0
	  @SPEC_comments = psic  User = epix
	  @SPEC_num_headers = 1
	  @default = S1
	  S1:NXentry
		@NX_class = NXentry
		@default = data
		Q:float64[3] = [0.99987000000000004, -3.6142500000000002e-05, 11.0068]
		  @description = hkl at start of scan
		T:float64 = 1.0
		  @units = s
		  @description = SPEC scan with constant counting time
		command:char[32] = ascan  eta 43.6355 44.0355  40 1
		comments:char[4] = psic
		counting_basis:char[37] = SPEC scan with constant counting time
		date:char[19] = 2003-07-17T02:38:24
		scan_number:char[1] = 1
		title:char[35] = 1  ascan  eta 43.6355 44.0355  40 1
		G:NXcollection
		  @NX_class = NXcollection
		  @description = SPEC geometry arrays, meanings defined by SPEC diffractometer support
		  G0:float64[21] = [0.0, 0.0, 0.0, '...', 0.0]
			@spec_name = G0
		  G1:float64[32] = [3.8250000000000002, 3.8879999999999999, 11.704000000000001, '...', 1.3809800000000001]
			@spec_name = G1
		  G2:float64 = 0.0
			@spec_name = G2
		MCA:NXcollection
		  @NX_class = NXcollection
		  @description = MCA metadata
		  first_saved:int32 = 1110
		  last_saved:int32 = 1200
		  number_saved:int32 = 1201
		  reduction_coef:float64 = 1.0
		data:NXdata
		  @NX_class = NXdata
		  @description = SPEC scan data
		  @signal = I0
		  @axes = eta
		  @eta_indices = [0]
		  Epoch:float64[41] = [54.0, 57.0, 59.0, '...', 150.0]
			@spec_name = Epoch
		  H:float64[41] = [0.99823099999999998, 0.99835799999999997, 0.99844100000000002, '...', 1.0014099999999999]
			@spec_name = H
		  I0:float64[41] = [1224.0, 1224.0, 1225.0, '...', 1222.0]
			@spec_name = I0
		  I00:float64[41] = [860.0, 861.0, 861.0, '...', 858.0]
			@spec_name = I00
		  I0_1:float64[41] = [1224.0, 1224.0, 1225.0, '...', 1222.0]
			@spec_name = I0_1
		  K:float64[41] = [-0.0136717, -0.012620299999999999, -0.0119303, '...', 0.0129094]
			@spec_name = K
		  Kalpha:float64[41] = [0.0, 0.0, 0.0, '...', 0.0]
			@spec_name = Kalpha
		  L:float64[41] = [11.008100000000001, 11.007999999999999, 11.007999999999999, '...', 11.0054]
			@spec_name = L
		  _mca_:float64[41,91] = __array
			__array = [
				[0.0, 0.0, 0.0, '...', 0.0]
				[0.0, 0.0, 0.0, '...', 0.0]
				[0.0, 0.0, 0.0, '...', 0.0]
				...
				[0.0, 0.0, 0.0, '...', 0.0]
			  ]
			@axes = eta:_mca_channel_
			@spec_name = _mca_
		  _mca_channel_:int32[91] = [1, 2, 3, '...', 91]
			@units = channel
			@spec_name = _mca_channel_
		  elastic:float64[41] = [1.0, 0.0, 0.0, '...', 0.0]
			@spec_name = elastic
		  eta:float64[41] = [43.628, 43.643999999999998, 43.654499999999999, '...', 44.032499999999999]
			@spec_name = eta
		  harmonic:float64[41] = [0.0, 0.0, 0.0, '...', 0.0]
			@spec_name = harmonic
		  seconds:float64[41] = [1.0, 1.0, 1.0, '...', 1.0]
			@spec_name = seconds
...

**Comment by Henry0422** [comment]
Hi Pete,

I didn't try running spec2nexus on the example data file 33id_spec.dat with 2016.0601.0 release. Currently, in my Windows, it installed release 2016.0216.0.

I have 2 converted hdf5 files generated from those 2 releases. 
- Here is the converted hdf5 file using 2016.0601.0 release:   https://drive.google.com/open?id=0B8a9oC4tegPndHVKNzFCOUY3UHM    (The size of this file is small since it didn't contain any MCA)
- This is the converted hdf5 file using 2016.0216.0:   https://drive.google.com/open?id=0B8a9oC4tegPnWjUta0pldnBiY0k
- And this is the original spec data file: https://drive.google.com/file/d/0B8a9oC4tegPnRnNHT1lDRzJtWlU/view?usp=sharing 


Thanks,

Henry

**Comment by prjemian** [comment]
Looks like your scans use 4 MCA channels.  No info in the file about MCA configuration, just the raw data.

For sure, your data files were caught up in the change with 2016.0601.0.   A revised regular expression key for the MCA data will solve the problem.  Should be an easy fix.  Hope to get to it over the weekend.

The only tricky part will be how spec2nexus learns how many different MCA channels to use.  Here's what it looks like now.

    @A 0 0 ...     means only a single MCA is used
    @A1 0 0 ...    means this is data for MCA 1
    @A2 0 0 ...    means this is data for MCA 2

and so on, still not hard to implement, the regexp pattern changes from '@A' to '@A\d*' (that works!)

(ref: https://www.cheatography.com/davechild/cheat-sheets/regular-expressions/)

take a bit longer to put the channel number logic in the code

**Comment by prjemian** [comment]
Which scenario applies to these lines in your example data file?  I notice they have identical length (256 values)

* [ ] part of one spectrum (concatenated as spec2nexus has been doing)
* [ ] four different MCA spectra (a new feature for spec2nexus)

    @A1 0 0 0 0 0 ...
    @A2 0 0 0 0 0 ...
    @A3 0 0 0 0 0 ...
    @A4 0 0 0 0 0 ...

**Comment by Henry0422** [comment]
Thanks for helping us. I see what you were saying, and it is really good if the regular expression key is able to detect MCA name with numbers in it. 

I believe they are four different MCA spectra. From your latest comment, I would like to ask you a simple question to about this new feature for spec2nexus.

Version 2016.0216.0 is able to read all 4 MCA from the original file and write them in one table in a new `hdf5` file. I am curious to know if we going to have 4 tables when the original data file has 4 different MCA?

Here is a screenshot (https://github.com/Beamlines-CanadianLightSource/SGM-Beamline/blob/master/doc/img/hdf5_contains_mca.png) of converted `hdf5` for **version 2016.0216.0** which contains 4 MCA in in one table (I am not sure if **table** is a proper word or not)

**Comment by prjemian** [comment]
You've asked the question I was asking you, in a different way.
Do you *want* to have four different "tables" (HDF5 datasets) or are you satisfied with having them all in one "table"?

My guess is you would prefer four separate datasets.  Then, you do not have to extract them later on.  Also, other software would be able to use them as separate data.

The current code, with the revised regular expression match, will put them all in one dataset.  And, that could be released today.

To separate them into four datasets will take a bit more effort as the code has made an assumption in handling MCA data based on only one spectrum reported in a scan, nut multiple spectra.  That change will improve the capability of spec2nexus, but will take a day or two more, given the current work queue.

**Comment by Henry0422** [comment]
Yes, in our case, four separate datasets would be better. If there will be lots of work to achieve this goal, then you probably don't have to implement this. 

Since I figured out a way to separate 4 MCA in 1 dataset. Here is the code:   https://github.com/Beamlines-CanadianLightSource/SGM-Beamline/blob/master/h5py_open_data.ipynb . It reads `spectra_example.hdf5` https://drive.google.com/file/d/0B8a9oC4tegPnWjUta0pldnBiY0k/view?pref=2&pli=1 .

**Comment by prjemian** [comment]
I'll continue work to write *n* MCA datasets. 

Basic idea is this:
* If the key is "@A", then only one MCA spectrum is collected.  
* If the key is "@A1", then be prepared to write more than one dataset.

In general, the code should be revised to be prepared for more than one MCA dataset.

Stay tuned...
