### ISSUE TITLE
pip install spec2nexus not getting correct version number

### ISSUE THREAD

**Issue by JPHammonds** [prjemian/spec2nexus#61]
I have tried this on OS X and Linux with anaconda python.  It seems that spec2nexus is no longer picking up the correct version number. 

Here is what I get with pip install on OS X. I  have also tried manually specifying version with ==2016.0829.0

(test1) Defiant:~ hammonds$ pip install spec2nexus
Collecting spec2nexus
Collecting numpy (from spec2nexus)
  Downloading numpy-1.11.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.9MB)
    100% |████████████████████████████████| 3.9MB 199kB/s 
Collecting MatPlotLib (from spec2nexus)
  Using cached matplotlib-1.5.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting h5py (from spec2nexus)
  Using cached h5py-2.6.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting cycler (from MatPlotLib->spec2nexus)
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting pytz (from MatPlotLib->spec2nexus)
  Downloading pytz-2016.6.1-py2.py3-none-any.whl (481kB)
    100% |████████████████████████████████| 481kB 1.2MB/s 
Collecting python-dateutil (from MatPlotLib->spec2nexus)
  Using cached python_dateutil-2.5.3-py2.py3-none-any.whl
Collecting pyparsing!=2.0.0,!=2.0.4,!=2.1.2,>=1.5.6 (from MatPlotLib->spec2nexus)
  Using cached pyparsing-2.1.8-py2.py3-none-any.whl
Collecting six (from h5py->spec2nexus)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: numpy, six, cycler, pytz, python-dateutil, pyparsing, MatPlotLib, h5py, spec2nexus
Successfully installed MatPlotLib-1.5.2 cycler-0.10.0 h5py-2.6.0 numpy-1.11.1 pyparsing-2.1.8 python-dateutil-2.5.3 pytz-2016.6.1 six-1.10.0 spec2nexus-0+unknown
(test1) Defiant:~ hammonds$

**Comment by prjemian** [comment]
same problem in other projects:
https://github.com/prjemian/punx/issues/24
https://github.com/prjemian/pvWebMonitor/issues/22

**Comment by prjemian** [comment]
consider alternative to versioneer, as used in https://github.com/prjemian/pyRestTable/blob/master/src/pyRestTable/__init__.py
