### ISSUE TITLE
specplot: more informative message when plot cannot be produced

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#69]
(from https://github.com/BCDA-APS/specplots/issues/2)

sometimes, a SPEC scan is aborted before data is written

right now, that results in a message such as this one:

    

Other times, when expecting a log Y axis but data is all zero, then:

**Comment by prjemian** [comment]
make it smart enough to look ahead in the scan block for a line such as this one:

    #C Tue Oct 04 14:33:02 2016.  Scan aborted after 0 points.

and show something more helpful instead of what is shown now

**Comment by prjemian** [comment]
`Scan aborted after 0 points.`

file | scan
----|------------
33bm_spec.dat | 15
CdSe | 10
user6idd.dat | 1

`Vertical axis all zero`

file | scan | X axis | Y axis
----|----|----|----
33bm_spec.dat | 1 | theta | sca1
CdSe | 11 | a7ay | FWD-D

**Comment by prjemian** [comment]
fyi: requested by @sureshnaps (via @jsullivan-anl)

**Comment by sureshnaps** [comment]
Thanks a lot Pete.
