### ISSUE TITLE
specplot: TypeError from mesh

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#84]
test file: 33id_spec.dat
scan 29 (and two others)

    #S 29 mesh eta 56.95 57.05 10 chi 90.92 91.02 10 1

produces exception:

    TypeError: Dimensions of C (11L, 8L) are incompatible with X (11) and/or Y (8); see help(pcolor)

ref:  http://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.pcolor.html

**Comment by prjemian** [comment]
same problem with pcolormesh()

**Comment by prjemian** [comment]
perhaps pcolor() or pcolormesh() are not the best choice for plotting this data.

**Comment by prjemian** [comment]
What does NeXpy do?

**Comment by prjemian** [comment]
start here: https://github.com/nexpy/nexpy/blob/master/src/nexpy/gui/plotview.py#L751

**Comment by rayosborn** [comment]
NeXpy uses `pcolormesh`, which expects the X and Y values to be pixel boundaries, not centers. In the previous function, `get_image` calls the function `boundaries`, which converts centers to boundaries - see  https://github.com/nexpy/nexpy/blob/master/src/nexpy/gui/plotview.py#L2593, which in turn calls  https://github.com/nexpy/nexpy/blob/master/src/nexpy/gui/plotview.py#L3823. If the grid is regular, I call `imshow`.

**Comment by prjemian** [comment]
The major problem here is that X & Y should be swapped.  That's why the shape of this 11 x 8 plot did not match the two arrays X & Y.  As @rayosborn said, `pcolormesh()` **is** the method to use when applying dimension scales.

**Comment by rayosborn** [comment]
`pcolormesh` will plot if X and Y has the same dimensions as the relevant 2D mesh shape, but the plot will have the axes shifted with respect to the image, since it assumes the X and Y values are pixel boundaries. If you look at http://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.pcolor.html, it states:

    pcolor(X, Y, C, **kwargs)

    Ideally the dimensions of X and Y should be one greater than those of C; if the dimensions are the     
    same, then the last row and column of C will be ignored.
